package es.nom.juanfranciscoruiz.utiles;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Test class for MiObjeto.
 * This is a class generated by Gemini AI to show me how to test classes that
 * print to standard output: redirect standard output to a byte array stream
 * and finally restore standard output.
 */
public class MiClaseTest {
  
  @Test
  public void testImpresionObjeto() {
    // Redirect standard output
    ByteArrayOutputStream outContent = new ByteArrayOutputStream();
    PrintStream originalOut = System.out;
    System.setOut(new PrintStream(outContent));
    
    // Create the object to print
    MiObjeto objeto = new MiObjeto("Hola, mundo!");
    
    // Call the method that prints the object
    objeto.imprimir();
    
    // Restore standard output
    System.setOut(originalOut);
    
    // Check the output
    String expectedOutput = "Hola, mundo!".concat(System.lineSeparator()); // Make sure it matches the print format
    assertEquals(expectedOutput, outContent.toString());
  }
}

