package es.nom.juanfranciscoruiz.ansiterm.codes;

import es.nom.juanfranciscoruiz.ansiterm.model.OSC;

/**
 * Utility class providing methods to generate ANSI escape sequences for setting
 * terminal window titles and icon names using Operating System Command (OSC) codes.
 * The escape sequences generated by this class are compatible with terminals
 * that support ANSI escape codes.
 */
public class WindowTitleCodes {
    /**
     * Private constructor. Class can't be instantiated by the user
     */
    private WindowTitleCodes() {}

    /**
     * Sequence......: ESC ] 0 ; string BEL | ST
     * Code..........: OSC 0
     * Description...: Set Window Title and Icon Name
     * Behavior......: Sets the terminal window title and the icon name to the specified string.
     *
     * @param title the title to set
     * @return the ANSI escape sequence
     */
    public static String setWindowTitle(String title) {
        return OSC.OSC + title + OSC.ST;
    }

    /**
     * Sequence......: ESC ] 2 ; string BEL | ST
     * Code..........: OSC 2
     * Description...: Set Window Title
     * Behavior......: Sets only the terminal window title to the specified string.
     *
     * @param title the title to set
     * @return the ANSI escape sequence
     */
    public static String updateWindowTitle(String title) {
        return OSC.OSC + "2;" + title + OSC.ST;
    }
}
