package es.nom.juanfranciscoruiz.utiles;

import es.nom.juanfranciscoruiz.utiles.model.MenuConstants;
import es.nom.juanfranciscoruiz.utiles.exceptions.MenuErrors;
import es.nom.juanfranciscoruiz.utiles.exceptions.MenuException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

import static es.nom.juanfranciscoruiz.utiles.Stuff.*;

/**
 * It's the representation of an options menu, capable of generating a view of
 * this menu for output devices or streams and for getting the user's
 * response.
 * <p>
 * This class is used in conjunction with the class MenuManager to manage and
 * display menus.
 * <p>
 * Most of the logic, management, and validation of this object is handled
 * through its associated class, MenuManager.
 * <p>
 * It is recommended to use MenuManager to perform operations on Menus, such as
 * adding, removing, adding, modifying, and deleting menus, or working with
 * their properties.
 *
 *
 * @author Juan F. Ruiz
 */
public class Menu {
    // static variables, resource bundles and constants
    /**
     * For debugging.
     */
    private final static Logger logger = LoggerFactory.getLogger(Menu.class);
    /**
     * A private static variable that holds a resource bundle for localized messages.
     * This is used to load and manage locale-specific resources, such as strings,
     * to support internationalization.
     */
    private static ResourceBundle messages;

    static {
        try {
            messages = ResourceBundle.getBundle("messages");
        } catch (MissingResourceException e) {
            logger.warn("ResourceBundle 'messages' not found. Falling back to default messages.");
            messages = null;
        }
    }
    /**
     * Helper method to fetch internationalized messages, falling back to default if not found.
     *
     * @param key            The ResourceBundle key
     * @param defaultMessage The default message if key or bundle is not available
     * @return The resolved message
     */
    private static String getMessage(String key, String defaultMessage) {
        if (messages != null && messages.containsKey(key)) {
            return messages.getString(key);
        }
        return defaultMessage;
    }
    /**
     * Default value for the title property of a Menu Object.
     */
    private static final String NO_TITLE = getMessage("msg.menu.no.title", MenuConstants.NO_TITLE);
    /**
     * For a Menu object that is the Home Menu this is the option 0 of the menu
     * for exiting the application.
     */
    private static final String EXITOPT = getMessage("msg.menu.exit.opt",MenuConstants.EXITOPT);
    /**
     * Default vale for the message shown to the user below the list options.
     */
    private static final String DEFAULT_MSG = getMessage("msg.menu.default.msg", MenuConstants.DEFAULT_MSG);
    /**
     * Constant for the wrong option.
     */
    public static final Long WRONG_OPTION = -1L;

    //Properties of the Menu object
    /**
     * Represents an instance of the {@code Menu} class.
     * This variable holds a reference to a {@code Menu} object
     * that could be used to manage or store menu-related behavior
     * or structure within the application.
     */
    private Menu instance;
    /**
     * List of options for the menu.
     */
    private List<String> options;
    /**
     * Title of the menu.
     */
    private String title;
    /**
     * Message to be displayed below the list of options.
     */
    private String message;
    /**
     * The option selected by the user.
     */
    private Long selectedOption;
    /**
     * Indicates whether this menu is the application's main menu.
     * If it is the root menu, the first option (option 0) will contain the text
     * "0. Exit the application" (the exact value depends on I18N, but not the
     * meaning). If it is not the root menu, the first option (option 0) will
     * contain the string "0. [BACK]" and will require the "parentMenu"
     * property to have a reference to another menu object that will be its parent.
     */
    private boolean isRootMenu;
    /**
     * Represents the layout or visual representation of a menu in the application.
     * This variable typically holds information about how the menu is displayed
     * or rendered, such as its configuration or style.
     * Their content will generated by the generateMenuView() method.
     */
    private String menuView;
    /**
     * The submenus of this menu, or null if this is a leaf menu.
     */
    private List<Menu> subMenus;
    /**
     * The parent menu of this menu, or null if this is a root menu.
     */
    private Menu parentMenu;

    // Constructors
    /**
     * Default constructor for the Menu class.
     * This constructor initializes the Menu object with default values, including
     * an empty options list, an empty submenu list, and default settings for root menu,
     * title, message, menu view, and the selected option.
     *
     * @throws MenuException if an error occurs during the initialization of the Menu object.
     */
    private Menu() throws MenuException {
        this.instance = this;
        this.setRootMenu(true);
        this.setParentMenu(null);
        this.setTitle(getMessage("msg.menu.no.title", MenuConstants.NO_TITLE));
        this.setMessage(getMessage("msg.menu.default.msg", MenuConstants.DEFAULT_MSG));
        this.menuView = "";
        this.setSelectedOption(0L);

        // By default, the default constructor builds a Menu Object of type "Root Menu"
        // and then, the first option is ALWAYS the exit option.
        this.options = new ArrayList<>();
        this.getOptions().addFirst( getMessage("msg.menu.exit.opt", MenuConstants.EXITOPT));
        this.subMenus = new ArrayList<>();
    }

    /**
     * Constructs a new Menu instance with the specified parameters.
     *
     * @param options    A list of options to be included in the menu. If the list is null or empty, no additional
     *                   options will be added except for the default root/back menu option.
     * @param title      The title of the menu. If null or empty, a default "no title" value will be assigned.
     * @param message    A message to be displayed in the menu. Can be null if no message is required.
     * @param isRootMenu Indicates whether the menu is the root menu or a sub-menu. If true, an "Exit" option will be
     *                   added as the first menu item, otherwise a "Back" option will be added.
     * @throws MenuException If an error occurs while creating or initializing the menu instance.
     */
    private Menu(List<String> options, String title, String message,
                boolean isRootMenu) throws MenuException {
        this();

        this.setRootMenu(isRootMenu);



        if (options != null && !options.isEmpty()) {
            for (String option : options) {
                this.addOption(option);
            }
        }

        if (title != null && !title.isEmpty()) {
            this.setTitle(title);
        } else {
            this.setTitle(getMessage("msg.menu.no.title", MenuConstants.NO_TITLE));
        }

        if (message != null) {
            this.setMessage(message);
        } else {
            this.setMessage(getMessage("msg.menu.default.msg", MenuConstants.DEFAULT_MSG));
        }
    }

    /**
     * Constructs a new Menu object with the specified options, title, message, root menu
     * status, submenus, and parent menu.
     *
     * @param options a list of string options available in the menu.
     * @param title the title of the menu.
     * @param message a message or description associated with the menu.
     * @param isRootMenu a boolean flag indicating whether this Menu is a root menu.
     * @param subMenus a list of submenus belonging to this menu; cannot be null.
     * @param parentMenu the parent menu of this menu; must be null if the menu is a root menu,
     *                   and must be non-null if the menu is a submenu.
     * @throws MenuException if any validation fails:
     *                       - when subMenus is null.
     *                       - when the menu is marked as a root menu but has a non-null parent menu.
     *                       - when the menu is a submenu but does not have a parent menu.
     */
    private Menu(List<String> options, String title, String message, boolean isRootMenu,
                List<Menu> subMenus, Menu parentMenu) throws MenuException {
        this(options, title, message, isRootMenu);
        if (subMenus == null) {
            String msg = getMessage("err.menu.submenus.null", MenuErrors.ERR_SUBMENUS_CANNOT_BE_NULL);
            throw new MenuException(msg);
        }
        this.setSubMenus(subMenus);
        if (isRootMenu) {
            if (parentMenu != null) {
                String msg = getMessage("err.menu.root.no.parent", MenuErrors.ERR_ROOTMENU_CANT_HAVE_A_PARENT_MENU);
                throw new MenuException(msg);
            }
        } else {
            if (parentMenu != null) {
                this.setParentMenu(parentMenu);
            } else {
                String msg = getMessage("err.menu.submenu.must.have.parent", MenuErrors.ERR_SUBMENU_MUST_HAVE_A_PARENT_MENU);
                throw new MenuException(msg);
            }
        }
    }

    //Getters and Setters
    /**
     * Retrieves an instance of the Menu class.
     * This method creates and returns a new Menu object.
     *
     * @return a new instance of the Menu class
     * @throws MenuException if an error occurs while creating the Menu instance
     */
    public static Menu getInstance() throws MenuException {
        return new Menu();
    }
    /**
     * Creates and returns an instance of the Menu class with the specified configuration.
     *
     * @param options     the list of options to be displayed in the menu
     * @param title       the title of the menu to be displayed
     * @param message     additional message or description for the menu
     * @param isRootMenu  indicates if the menu is a root menu
     * @param subMenus    the list of submenus associated with this menu
     * @param parentMenu  the parent menu of this menu, or null if it does not have one
     * @return a new instance of the Menu class with the specified properties
     * @throws MenuException if an error occurs while creating the menu
     */
    public Menu getInstance(List<String> options, String title, String message, boolean isRootMenu, List<Menu> subMenus, Menu parentMenu) throws MenuException {
        return new Menu(options, title, message, isRootMenu, subMenus, parentMenu);
    }
    /**
     * Creates and returns an instance of the Menu object.
     *
     * @param options    a list of menu options that will be displayed.
     * @param title      the title of the menu.
     * @param message    the message or description associated with the menu.
     * @param isRootMenu a boolean indicating whether this menu is a root menu.
     * @return an instance of the Menu object initialized with the provided parameters.
     * @throws MenuException if there is an error while creating the menu instance.
     */
    public static Menu getInstance(List<String> options, String title, String message, boolean isRootMenu) throws MenuException{
        return new Menu(options, title, message, isRootMenu);
    }
    /**
     * Gets the list of menu options
     *
     * @return A list of strings with the options.
     */
    public List<String> getOptions() {
        return options;
    }

    /**
     * Sets a list of options for the menu.
     *
     *  <p>
     *  <b style='color:red'>Note:</b> Remember, the numeration of the options is set and validated by the MenuManager class!
     *  </p>
     * @param options the list of options to be set; must not be null
     * @throws MenuException if the provided options list is null
     */
    public void setOptions(List<String> options) throws MenuException {
        if (options == null) {
            String msg = getMessage("err.menu.options.null", MenuErrors.ERR_OPTIONS_CANNOT_BE_NULL);
            throw new MenuException(msg);
        }

        // Set the list of options.
        if (this.getOptions() != null) {
            this.options.addAll(options);
        } else {
            this.options = options;
        }

        // The first option of the menu is added automatically and depends from 'rootMenu' property.
        setTheFirstOption(this.getIsRootMenu());
    }

    /**
     * Gets the menu title
     *
     * @return a string with the menu title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Set the menu title.
     * The title can't be null for a valid menu object.
     *
     * @param title A chain with the new menu title
     * @throws MenuException If the title is null
     */
    public void setTitle(String title) throws MenuException {
        if (title == null) {
            String msg = getMessage("err.menu.title.null", MenuErrors.ERR_TITLE_CANNOT_BE_NULL);
            throw new MenuException(msg);
        }
        this.title = title;
    }

    /**
     * Gets the message from the menu
     *
     * @return a string with the current menu message
     */
    public String getMessage() {
        return message;
    }

    /**
     * Set a new message in the menu.
     * A valid message can't be null.
     *
     * @param message A string with the new menu message
     * @throws MenuException If the message is null
     */
    public void setMessage(String message) throws MenuException {
        if (message == null) {
            String msg = getMessage("err.menu.message.null", MenuErrors.ERR_MESSAGE_CANNOT_BE_NULL);
            throw new MenuException(msg);
        }
        this.message = message;
    }

    /**
     * Gets the option currently selected by the user (after calling the
     * awaitResponse() method).
     *
     * @return a long with the option selected by the user
     */
    public Long getSelectedOption() {
        return selectedOption;
    }

    /**
     * Set the selected option
     *
     * @param selectedOption A long file with the selected option
     */
    public void setSelectedOption(Long selectedOption) {
        this.selectedOption = selectedOption;
    }

    /**
     * Returns a boolean indicating whether this menu is the application's main
     * menu.
     *
     * @return a boolean, if true it indicates that the current menu is the main
     * menu (root menu) of the application and false otherwise.
     */
    public boolean getIsRootMenu() {
        return isRootMenu();
    }


    /**
     * Retrieves the parent Menu for the current menu instance.
     *
     * @return the parent Menu if it exists, or null if there is no parent Menu
     */
    public Menu getParentMenu() {
        if (parentMenu == null) {
            return null;
        }
        return parentMenu;
    }

    /**
     * Sets the parent menu for this menu instance.
     * If the provided parent menu is null, this method ensures that the current menu is a root menu.
     * If a non-null parent menu is provided, this method validates that the current menu is not a root menu
     * and that the parent menu is not the same as the current menu.
     *
     * @param parentMenu the menu to be set as the parent of this menu. Can be null if this menu is a root menu.
     * @throws MenuException if an error occurs while setting the parent menu.
     */
    public void setParentMenu(Menu parentMenu) throws MenuException {
        if (parentMenu == null) {
            if (!this.isRootMenu()){
                String msg = getMessage("err.menu.submenu.must.have.parent", MenuErrors.ERR_SUBMENU_MUST_HAVE_A_PARENT_MENU);
                throw new MenuException(msg);
            }
        } else {
            if (this.isRootMenu) {
                String msg = getMessage("err.menu.root.no.parent", MenuErrors.ERR_ROOTMENU_CANT_HAVE_A_PARENT_MENU);
                throw new MenuException(msg);
            }
            if (parentMenu.equals(this)) {
                String msg = getMessage("err.menu.cannot.have.itself.parent", MenuErrors.ERR_MENU_CANNOT_HAVE_ITSELF_AS_PARENT);
                throw new MenuException(msg);
            }
        }
        this.parentMenu = parentMenu;
    }

    /**
     * Disables the link to the root menu by setting the parent menu to null and
     * marking the current menu as the root menu.
     *
     * @param parentMenu the parent menu to be detached; must not be null
     * @throws MenuException if the provided parent menu is null
     */
    public void disableLinkToRootMenu(Menu parentMenu) throws MenuException {
         if (parentMenu == null) {
             throw new MenuException(getMessage("err.menu.null", MenuErrors.ERR_MENU_OBJECT_CANNOT_BE_NULL));
         }
         this.parentMenu = null;
         this.isRootMenu = true;
         setTheFirstOption(true);
    }


    /**
     * Sets whether the current menu is a root menu or not.
     * A root menu is the top-level menu that does not have a parent menu.
     * This method also adjusts options accordingly based on the root menu state.
     *
     * @param isRootMenu a boolean indicating if the current menu is a root menu.
     *                   If true, the menu is designated as a root menu;
     *                   otherwise, it is considered a sub-menu.
     * @throws MenuException if the current menu has a parent menu and is being set as a root menu.
     */
    public void setIsRootMenu(boolean isRootMenu) throws MenuException {
        if (this.getParentMenu() != null) {
            String msg = getMessage("err.menu.submenu.set.root", MenuErrors.ERR_SUBMENU_SET_AS_ROOT);
            throw new MenuException(msg);
        }
        this.setRootMenu(isRootMenu);

        if (this.getOptions() == null) {
            this.setOptions(new ArrayList<>());
        }

        this.setTheFirstOption(this.getIsRootMenu());
    }

    /**
     * Retrieves the current state of the menu view as a String.
     * The menu view is generated internally before being returned.
     *
     * @return the generated menu view as a String
     */
    public String getMenuView() {
        this.generateMenuView();
        return this.menuView;
    }

    /**
     * Generates a formatted menu view and sets it to the corresponding field.
     * <p>
     * This method constructs a visual representation of a menu using the instance's
     * title, options, and a message. The title is formatted with decorative borders,
     * each option is displayed in sequence, and the message is appended at the end.
     * The final formatted menu view is stored in the appropriate field using
     * the {@code setMenuView} method.
     * <p>
     * The menu structure includes:
     * <ul>
     * <li>- A title surrounded by star borders that adjust to the title's length.</li>
     * <li>- A list of options provided by the instance's {@code getOptions} method.</li>
     * <li>- A concluding message provided by the instance's {@code getMessage} method.</li>
     * </ul>
     */
    public void generateMenuView() {
        final String LS = System.lineSeparator();
        StringBuilder sb = new StringBuilder();
        StringBuilder sbMenuView = new StringBuilder();

        sb.append(LS);
        int longitud = this.getTitle().length();
        String repeat = "*".repeat(Math.max(0, longitud + 5));
        sb.append(repeat);

        sb.append(LS);
        sb.append("  ").append(this.getTitle()).append("  ");
        sb.append(LS);
        sb.append(repeat);

        String tit = sb.toString();
        sbMenuView.append(tit);
        sbMenuView.append(LS);
        sbMenuView.append(LS);
        for (String opcion : this.getOptions()) {
            sbMenuView.append(opcion);
            sbMenuView.append(LS);
        }
        sbMenuView.append(LS);
        sbMenuView.append(this.getMessage());
        sbMenuView.append(LS);
        this.menuView = sbMenuView.toString();
    }


    /**
     * In the case that an application has several menus, if isRootMenu is true,
     * then this is the main menu of the application and the option "0. Exit the
     * application" will be added as the first option.
     *
     * @return true if this is the root menu, false otherwise
     */
    public boolean isRootMenu() {
        return isRootMenu;
    }

    /**
     * Sets the root menu status.
     *
     * @param rootMenu A boolean indicating whether this menu should be set as the root menu.
     */
    public void setRootMenu(boolean rootMenu) {
        isRootMenu = rootMenu;
    }

    /**
     * Gets the list of submenus for this menu.
     *
     * @return a list of submenus for this menu.
     */
    public List<Menu> getSubMenus() {
        return subMenus;
    }

    /**
     * Sets the list of submenus for this menu. Each submenu will have its parent menu
     * set to the current menu, and their titles will be added to the options list. However,
     * the submenus will be rendered with a different style in the generateMenuView() method.
     *
     * @param subMenus the list of submenus to be associated with the current menu
     * @throws MenuException if an error occurs while setting the submenus
     */
    public void setSubMenus(List<Menu> subMenus) throws MenuException {
        if (subMenus == null) {
            this.subMenus = null;
            return;
        }

        // Defensive copying: avoids fixed-size (Arrays.asList) or non-modifiable lists
        List<Menu> mutable = new ArrayList<>(subMenus);

        // The submenus will added to the options list too but renders with different
        // style in generateMenuView() method.
        for (Menu subMenu : mutable) {
            subMenu.setParentMenu(this);
            this.addOption(subMenu.getTitle());
        }
        this.subMenus = mutable;
    }

    // Methods of the object Menu.
    /**
     * Adds a submenu to this menu.
     * Note: when adding a submenu, their title will be added to the options list.
     *
     * @param childMenu The submenu to add.
     * @throws MenuException If the child menu is this menu or if the child menu is a root menu.
     */
    public void addSubMenu(Menu childMenu) throws MenuException {
       try {
           childMenu.setParentMenu(this);
           this.subMenus.add(childMenu);
           this.addOption(childMenu.getTitle());
       } catch (Exception e) {
           throw new MenuException(e.getMessage());
       }
    }

    /**
     * Removes a submenu from the list of submenus.
     *
     * @param childMenu the submenu to remove
     * @throws MenuException if an error occurs during the removal process
     */
    public void removeSubMenu(Menu childMenu) throws MenuException {
        if (childMenu == null) {
            throw new MenuException(getMessage("err.menu.submenu.null", MenuErrors.ERR_SUBMENU_CANNOT_BE_NULL));
        }
        this.options.remove(childMenu.getTitle());
        childMenu.disableLinkToRootMenu(this);

        if (!this.subMenus.remove(childMenu)){
            throw new MenuException(getMessage("err.menu.submenu.not.found", MenuErrors.ERR_SUBMENU_NOT_FOUND));
        }
    }

    /**
     * Adds a new option to the menu.
     *
     * @param optionText the text of the option to be added
     * @throws MenuException if an error occurs while adding the option
     */
    public void addOption(String optionText) throws MenuException {
        try {
            this.getOptions().add(optionText);
        } catch (Exception e) {
            throw new MenuException(e.getMessage());
        }
    }



    /**
     * Removes an option from the options list.
     *
     * @param optionText The option to remove.
     *                   Must not be null or empty.
     * @throws MenuException If the provided option is null or empty.
     */
    public void removeOption(String optionText) throws MenuException {
        if (optionText == null || optionText.isEmpty()) {
            throw new MenuException(getMessage("err.menu.option.null.or.empty", MenuErrors.ERR_OPTION_CANNOT_BE_NULL_OR_EMPTY));
        }
        this.getOptions().remove(optionText);

    }

    /**
     * Generates a string representation of the Menu object.
     * Don't show the menuview property because of their length.
     *
     * @return A string containing the state and attributes of the Menu object,
     * including its options, title, message, selected option, root menu status,
     * parent menu title (if present), and a summary of its sub-menus.
     */
    @Override
    public String toString() {
        return SL + "Menu{" + SL +
                "\toptions=" + CollectionToString(this.getOptions(), true, 20) + SL +
                "\ttitle=" + this.getTitle() + SL +
                "\tmessage=" + this.getMessage() + SL +
                "\tselectedOption=" + this.getSelectedOption() + SL +
                "\tisRootMenu=" + this.getIsRootMenu() + SL +
                "\tparentMenu=" + (this.getParentMenu() != null ?
                this.getParentMenu().getTitle() : "null") + SL +
                "\tsubMenus=" + CollectionToString(this.getSubMenus(), true, 20) + SL +
                '}';
    }



    /**
     * Sets the first option of the menu based on whether the current menu is a root menu or a sub-menu.
     * For a root menu, the first option will be "Exit".
     * For a sub-menu or child menu, the first option will be "Back".
     *
     * @param isRootMenu indicates whether the current menu is a root menu.
     *                   If true, the menu is treated as a root menu;
     *                   otherwise, it is treated as a sub-menu or child menu.
     */
    private void setTheFirstOption(boolean isRootMenu) {
        // The first option of the menu is added automatically and depends from 'rootMenu' property.
        if (this.isRootMenu()) {
            // It's a 'Root Menu, the first option is 'Exit'
            if (this.getOptions() != null && !this.getOptions().isEmpty()){
                this.getOptions().removeFirst();
                this.getOptions().addFirst(getMessage("msg.menu.exit.opt", MenuConstants.EXITOPT));
            }
        } else {
            // It's a 'Sub Menu or Child Menu, the first option is 'Back'
            if (this.getOptions() != null && !this.getOptions().isEmpty()){
                this.getOptions().removeFirst();
                this.getOptions().addFirst(getMessage("msg.menu.back.opt", MenuConstants.BACKTOPARENTMENU));
            }
        }
    }
}