package es.nom.juanfranciscoruiz.utiles.exceptions;

/**
 * Custom exception class for MenuManager operations.
 */
public class MenuManagerException extends Exception{

    /**
     * A unique identifier for this class, used during the serialization and deserialization
     * process to verify that the sender and receiver of a serialized object have loaded
     * classes for that object that are compatible with respect to serialization.
     *
     * This ID ensures that if there are changes to the class definition (e.g., adding or
     * removing fields, modifying methods), they can be detected during deserialization.
     *
     * It is recommended to explicitly declare this field to avoid relying on the default
     * value generated by the Java runtime, which may change between compilations.
     */
    private static final long serialVersionUID = 1L;

    /**
     * Constructs a new instance of {@code MenuManagerException} with no detail message.
     * This constructor initializes the exception without providing any information
     * about the cause or context of the error. It is typically used when a more
     * descriptive message is unnecessary or unavailable.
     */
    public MenuManagerException() {
        super();
    }

    /**
     * Constructs a new MenuManagerException with the specified detail message.
     *
     * @param message the detail message to describe the exception.
     *                This message is accessible later through the
     *                {@link Throwable#getMessage()} method.
     */
    public MenuManagerException(String message) {
        super(message);
    }

    /**
     * Constructs a new MenuManagerException with the specified detail message
     * and cause. This constructor allows the inclusion of both a custom error
     * message and an underlying cause (e.g., another exception) for more
     * informative error handling and debugging.
     *
     * @param message the detail message to describe the exception.
     *                This message is accessible later through the
     *                {@link Throwable#getMessage()} method.
     * @param cause   the underlying cause of this exception. The cause is
     *                saved and can be retrieved later with the
     *                {@link Throwable#getCause()} method. A null value
     *                indicates that the cause is unknown or nonexistent.
     */
    public MenuManagerException(String message, Throwable cause) {
        super(message, cause);
    }

    /**
     * Constructs a new MenuManagerException with the specified cause.
     *
     * @param cause the cause (which is saved for later retrieval by the {@link #getCause()} method).
     *              A {@code null} value is permitted, and indicates that the cause is nonexistent or unknown.
     */
    public MenuManagerException(Throwable cause) {
        super(cause);
    }

}
